//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ArtTrash.ReportsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback CR_OportunidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback EjecutarReporteOperationCompleted;
        
        private System.Threading.SendOrPostCallback EjecutarReporte1OperationCompleted;
        
        private System.Threading.SendOrPostCallback CR_OrdenServicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CR_VentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CR_StockOperationCompleted;
        
        private System.Threading.SendOrPostCallback CR_SalesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::ArtTrash.Properties.Settings.Default.ArtTrash_ReportsService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event TestPDFCompletedEventHandler TestPDFCompleted;
        
        /// <remarks/>
        public event CR_OportunidadCompletedEventHandler CR_OportunidadCompleted;
        
        /// <remarks/>
        public event EjecutarReporteCompletedEventHandler EjecutarReporteCompleted;
        
        /// <remarks/>
        public event EjecutarReporte1CompletedEventHandler EjecutarReporte1Completed;
        
        /// <remarks/>
        public event CR_OrdenServicioCompletedEventHandler CR_OrdenServicioCompleted;
        
        /// <remarks/>
        public event CR_VentaCompletedEventHandler CR_VentaCompleted;
        
        /// <remarks/>
        public event CR_StockCompletedEventHandler CR_StockCompleted;
        
        /// <remarks/>
        public event CR_SalesCompletedEventHandler CR_SalesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestPDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TestPDF(int idOportunidad) {
            this.Invoke("TestPDF", new object[] {
                        idOportunidad});
        }
        
        /// <remarks/>
        public void TestPDFAsync(int idOportunidad) {
            this.TestPDFAsync(idOportunidad, null);
        }
        
        /// <remarks/>
        public void TestPDFAsync(int idOportunidad, object userState) {
            if ((this.TestPDFOperationCompleted == null)) {
                this.TestPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestPDFOperationCompleted);
            }
            this.InvokeAsync("TestPDF", new object[] {
                        idOportunidad}, this.TestPDFOperationCompleted, userState);
        }
        
        private void OnTestPDFOperationCompleted(object arg) {
            if ((this.TestPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestPDFCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CR_Oportunidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CR_Oportunidad(int idOportunidad) {
            object[] results = this.Invoke("CR_Oportunidad", new object[] {
                        idOportunidad});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void CR_OportunidadAsync(int idOportunidad) {
            this.CR_OportunidadAsync(idOportunidad, null);
        }
        
        /// <remarks/>
        public void CR_OportunidadAsync(int idOportunidad, object userState) {
            if ((this.CR_OportunidadOperationCompleted == null)) {
                this.CR_OportunidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCR_OportunidadOperationCompleted);
            }
            this.InvokeAsync("CR_Oportunidad", new object[] {
                        idOportunidad}, this.CR_OportunidadOperationCompleted, userState);
        }
        
        private void OnCR_OportunidadOperationCompleted(object arg) {
            if ((this.CR_OportunidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CR_OportunidadCompleted(this, new CR_OportunidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EjecutarReporte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] EjecutarReporte(string archivoReporte, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] KeyValuePairOfStringObject[] parametros) {
            object[] results = this.Invoke("EjecutarReporte", new object[] {
                        archivoReporte,
                        parametros});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void EjecutarReporteAsync(string archivoReporte, KeyValuePairOfStringObject[] parametros) {
            this.EjecutarReporteAsync(archivoReporte, parametros, null);
        }
        
        /// <remarks/>
        public void EjecutarReporteAsync(string archivoReporte, KeyValuePairOfStringObject[] parametros, object userState) {
            if ((this.EjecutarReporteOperationCompleted == null)) {
                this.EjecutarReporteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEjecutarReporteOperationCompleted);
            }
            this.InvokeAsync("EjecutarReporte", new object[] {
                        archivoReporte,
                        parametros}, this.EjecutarReporteOperationCompleted, userState);
        }
        
        private void OnEjecutarReporteOperationCompleted(object arg) {
            if ((this.EjecutarReporteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EjecutarReporteCompleted(this, new EjecutarReporteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EjecutarReporte1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] EjecutarReporte1(string archivoReporte, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] KeyValuePairOfStringObject[] parametros) {
            object[] results = this.Invoke("EjecutarReporte1", new object[] {
                        archivoReporte,
                        parametros});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void EjecutarReporte1Async(string archivoReporte, KeyValuePairOfStringObject[] parametros) {
            this.EjecutarReporte1Async(archivoReporte, parametros, null);
        }
        
        /// <remarks/>
        public void EjecutarReporte1Async(string archivoReporte, KeyValuePairOfStringObject[] parametros, object userState) {
            if ((this.EjecutarReporte1OperationCompleted == null)) {
                this.EjecutarReporte1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEjecutarReporte1OperationCompleted);
            }
            this.InvokeAsync("EjecutarReporte1", new object[] {
                        archivoReporte,
                        parametros}, this.EjecutarReporte1OperationCompleted, userState);
        }
        
        private void OnEjecutarReporte1OperationCompleted(object arg) {
            if ((this.EjecutarReporte1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EjecutarReporte1Completed(this, new EjecutarReporte1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CR_OrdenServicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CR_OrdenServicio(int idOrdenServicio) {
            object[] results = this.Invoke("CR_OrdenServicio", new object[] {
                        idOrdenServicio});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void CR_OrdenServicioAsync(int idOrdenServicio) {
            this.CR_OrdenServicioAsync(idOrdenServicio, null);
        }
        
        /// <remarks/>
        public void CR_OrdenServicioAsync(int idOrdenServicio, object userState) {
            if ((this.CR_OrdenServicioOperationCompleted == null)) {
                this.CR_OrdenServicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCR_OrdenServicioOperationCompleted);
            }
            this.InvokeAsync("CR_OrdenServicio", new object[] {
                        idOrdenServicio}, this.CR_OrdenServicioOperationCompleted, userState);
        }
        
        private void OnCR_OrdenServicioOperationCompleted(object arg) {
            if ((this.CR_OrdenServicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CR_OrdenServicioCompleted(this, new CR_OrdenServicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CR_Venta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CR_Venta(int idVenta) {
            object[] results = this.Invoke("CR_Venta", new object[] {
                        idVenta});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void CR_VentaAsync(int idVenta) {
            this.CR_VentaAsync(idVenta, null);
        }
        
        /// <remarks/>
        public void CR_VentaAsync(int idVenta, object userState) {
            if ((this.CR_VentaOperationCompleted == null)) {
                this.CR_VentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCR_VentaOperationCompleted);
            }
            this.InvokeAsync("CR_Venta", new object[] {
                        idVenta}, this.CR_VentaOperationCompleted, userState);
        }
        
        private void OnCR_VentaOperationCompleted(object arg) {
            if ((this.CR_VentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CR_VentaCompleted(this, new CR_VentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CR_Stock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CR_Stock(int idMarca, int idEvento) {
            object[] results = this.Invoke("CR_Stock", new object[] {
                        idMarca,
                        idEvento});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void CR_StockAsync(int idMarca, int idEvento) {
            this.CR_StockAsync(idMarca, idEvento, null);
        }
        
        /// <remarks/>
        public void CR_StockAsync(int idMarca, int idEvento, object userState) {
            if ((this.CR_StockOperationCompleted == null)) {
                this.CR_StockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCR_StockOperationCompleted);
            }
            this.InvokeAsync("CR_Stock", new object[] {
                        idMarca,
                        idEvento}, this.CR_StockOperationCompleted, userState);
        }
        
        private void OnCR_StockOperationCompleted(object arg) {
            if ((this.CR_StockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CR_StockCompleted(this, new CR_StockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CR_Sales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CR_Sales(int idMarca, int idEvento) {
            object[] results = this.Invoke("CR_Sales", new object[] {
                        idMarca,
                        idEvento});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void CR_SalesAsync(int idMarca, int idEvento) {
            this.CR_SalesAsync(idMarca, idEvento, null);
        }
        
        /// <remarks/>
        public void CR_SalesAsync(int idMarca, int idEvento, object userState) {
            if ((this.CR_SalesOperationCompleted == null)) {
                this.CR_SalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCR_SalesOperationCompleted);
            }
            this.InvokeAsync("CR_Sales", new object[] {
                        idMarca,
                        idEvento}, this.CR_SalesOperationCompleted, userState);
        }
        
        private void OnCR_SalesOperationCompleted(object arg) {
            if ((this.CR_SalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CR_SalesCompleted(this, new CR_SalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValuePairOfStringObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TestPDFCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CR_OportunidadCompletedEventHandler(object sender, CR_OportunidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CR_OportunidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CR_OportunidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EjecutarReporteCompletedEventHandler(object sender, EjecutarReporteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EjecutarReporteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EjecutarReporteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EjecutarReporte1CompletedEventHandler(object sender, EjecutarReporte1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EjecutarReporte1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EjecutarReporte1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CR_OrdenServicioCompletedEventHandler(object sender, CR_OrdenServicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CR_OrdenServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CR_OrdenServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CR_VentaCompletedEventHandler(object sender, CR_VentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CR_VentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CR_VentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CR_StockCompletedEventHandler(object sender, CR_StockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CR_StockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CR_StockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CR_SalesCompletedEventHandler(object sender, CR_SalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CR_SalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CR_SalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591